[package]
name = "image-manipulation"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-siv = "0.7.0"
clap = { version = "4.5.45", features = ["derive"] }
image = "0.25.6"
iced = { version = "0.13.1", features = ["image"] }
rfd = "0.15.4"
